export type Dino = { slug: string; name: string; power: number };

export const DINOS: Dino[] = [
  { slug: "tyrannosaurus", name: "Tyrannosaurus Rex", power: 95 },
  { slug: "spinosaurus", name: "Spinosaurus", power: 97 },
  { slug: "giganotosaurus", name: "Giganotosaurus", power: 93 },
  { slug: "carcharodontosaurus", name: "Carcharodontosaurus", power: 90 },
  { slug: "allosaurus", name: "Allosaurus", power: 78 },
  { slug: "velociraptor", name: "Velociraptor", power: 55 },
  { slug: "utahraptor", name: "Utahraptor", power: 72 },
  { slug: "deinonychus", name: "Deinonychus", power: 62 },
  { slug: "dilophosaurus", name: "Dilophosaurus", power: 58 },
  { slug: "compsognathus", name: "Compsognathus", power: 15 },
  { slug: "oviraptor", name: "Oviraptor", power: 30 },
  { slug: "gallimimus", name: "Gallimimus", power: 35 },
  { slug: "therizinosaurus", name: "Therizinosaurus", power: 68 },
  { slug: "carnotaurus", name: "Carnotaurus", power: 80 },
  { slug: "ceratosaurus", name: "Ceratosaurus", power: 70 },
  { slug: "baryonyx", name: "Baryonyx", power: 74 },
  { slug: "suchomimus", name: "Suchomimus", power: 76 },
  { slug: "majungasaurus", name: "Majungasaurus", power: 65 },
  { slug: "acrocanthosaurus", name: "Acrocanthosaurus", power: 85 },
  { slug: "mapusaurus", name: "Mapusaurus", power: 88 },
  { slug: "brachiosaurus", name: "Brachiosaurus", power: 82 },
  { slug: "diplodocus", name: "Diplodocus", power: 75 },
  { slug: "apatosaurus", name: "Apatosaurus", power: 78 },
  { slug: "argentinosaurus", name: "Argentinosaurus", power: 98 },
  { slug: "mamenchisaurus", name: "Mamenchisaurus", power: 80 },
  { slug: "camarasaurus", name: "Camarasaurus", power: 67 },
  { slug: "triceratops", name: "Triceratops", power: 72 },
  { slug: "styracosaurus", name: "Styracosaurus", power: 60 },
  { slug: "pachyrhinosaurus", name: "Pachyrhinosaurus", power: 58 },
  { slug: "protoceratops", name: "Protoceratops", power: 25 },
  { slug: "stegosaurus", name: "Stegosaurus", power: 63 },
  { slug: "kentrosaurus", name: "Kentrosaurus", power: 48 },
  { slug: "ankylosaurus", name: "Ankylosaurus", power: 70 },
  { slug: "euoplocephalus", name: "Euoplocephalus", power: 65 },
  { slug: "pachycephalosaurus", name: "Pachycephalosaurus", power: 40 },
  { slug: "iguanodon", name: "Iguanodon", power: 50 },
  { slug: "parasaurolophus", name: "Parasaurolophus", power: 45 },
  { slug: "corythosaurus", name: "Corythosaurus", power: 42 },
  { slug: "edmontosaurus", name: "Edmontosaurus", power: 52 },
  { slug: "maiasaura", name: "Maiasaura", power: 38 },
  { slug: "microraptor", name: "Microraptor", power: 10 },
];

export const TOTAL_CARDS = DINOS.length; // 41
